### ISSUE TITLE
Provided script doesn't add dev dependencies

### ISSUE THREAD

**Issue by Frikki** [TylorS/lib-starter#1]
**Code to reproduce the issue:**

```
git clone https://github.com/TylorS/lib-starter LIBRARY_NAME

cd LIBRARY_NAME

rm -rf .git

git init

node .scripts/addDevDependencies.sh
```

**Expected behavior:**

The list of dev dependencies in _.scripts/addDevDependencies.sh_:

```
@motorcycle/tslint
@types/mocha
@types/node
commitizen
conventional-changelog-cli
cz-conventional-changelog
glob-expand
husky
mocha
ts-node
tslint
typescript
validate-commit-message
```

should be added to `devDependencies` in _package.json_.

**Actual behavior:**

The list, safe `@motorcycle/tslint` and `@types/mocha` are added to `dependencies` instead.

**Comment by TylorS** [comment]
This has been fixed!
